"""Regenerate the "What the ids on this page mean" block in each doc.

The docs are full of bare ids — `DF-05`, `PM-08`, `D-020` — and a reader has
no way to resolve them without opening two other files. Worse, several ids
that appear in CHANGELOG.md (`PM-01`, `OT-04`, `CMP-05`) refer to scenarios
that no longer exist, and nothing on the page says so.

This scans each doc for the ids it actually uses and rewrites a reference
table at the bottom, listing only those. Generated rather than hand-written
because the set drifts every time a scenario is added or retired, and a stale
glossary is worse than none.

    python -m scripts.build_id_reference          # rewrite
    python -m scripts.build_id_reference --check  # fail if any doc is stale

Four provenances, and the distinction is the useful part:
  live     — in evals/scenarios.py now, so the question shown is what runs
  designed — in PRD §7 but never implemented
  retired  — existed once, deleted; recoverable from git
  decision — a docs/decisions.md entry
"""

from __future__ import annotations

import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

BEGIN = "<!-- BEGIN id-reference (generated by scripts/build_id_reference.py) -->"
END = "<!-- END id-reference -->"

SCENARIO_RE = re.compile(r"\b(?:DF|CMP|MT|AMB|PM|UN|OT|INJ|CF|STR)-\d{2}\b")
DECISION_RE = re.compile(r"\bD-0\d{2}\b")

# The commit that still held the 25 authored-but-never-run scenarios, deleted
# in D-022. Used to explain ids that appear in older CHANGELOG entries.
RETIRED_SCENARIOS_REF = "f79b556:evals/scenarios.py"

TARGETS = [
    ("docs/reflection.md", True, True),
    ("README.md", True, True),
    ("evals/README.md", True, True),
    # decisions.md defines the D-numbers itself, so only scenarios are useful.
    ("docs/decisions.md", True, False),
    ("CHANGELOG.md", True, True),
]


def _live_scenarios() -> dict[str, str]:
    sys.path.insert(0, str(ROOT))
    from evals.scenarios import GOLDEN_SCENARIOS

    return {s.id: " → ".join(f'"{t}"' for t in s.turns) for s in GOLDEN_SCENARIOS}


def _prd_scenarios() -> dict[str, str]:
    """Parse the id/turn tables in PRD §7."""
    text = (ROOT / "docs/plans/02-prd.md").read_text()
    out: dict[str, str] = {}
    for line in text.splitlines():
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) >= 2 and SCENARIO_RE.fullmatch(cells[0]):
            out.setdefault(cells[0], cells[1])
    return out


def _retired_scenarios() -> dict[str, str]:
    try:
        blob = subprocess.check_output(
            ["git", "show", RETIRED_SCENARIOS_REF], cwd=ROOT, text=True
        )
    except Exception:
        return {}
    out: dict[str, str] = {}
    # id="XX-00" ... turns=["...", ...]. Parsed rather than imported: that file
    # is a deleted revision. literal_eval matters because the source wraps long
    # turns across adjacent string literals, which Python joins and a plain
    # regex would render as several separate turns.
    for match in re.finditer(r'id="([A-Z]+-\d{2})".*?turns=\[(.*?)\](?:,\s*\n)', blob, re.S):
        body = match.group(2)
        try:
            turns = ast.literal_eval("[" + body + "]")
        except Exception:
            # e.g. `_LONG_PREFIX + "..."`, not a literal. Fall back to the
            # fragments, joined, which is still readable.
            turns = ["".join(re.findall(r'"((?:[^"\\]|\\.)*)"', body))]
        turns = [t for t in turns if isinstance(t, str)]
        if turns:
            shown = " → ".join(f'"{_truncate(t)}"' for t in turns)
            out.setdefault(match.group(1), shown)
    return out


def _truncate(text: str, limit: int = 110) -> str:
    text = " ".join(text.split())
    return text if len(text) <= limit else text[:limit].rstrip() + "…"


def _decisions() -> dict[str, str]:
    text = (ROOT / "docs/decisions.md").read_text()
    out: dict[str, str] = {}
    for match in re.finditer(
        r"^## (D-0\d{2})(?: \N{EM DASH} |: | - )(.+?)\s*"
        r"(?:\(\d{4}-\d{2}-\d{2}.*?\))?$",
        text,
        re.M,
    ):
        out[match.group(1)] = match.group(2).strip()
    return out


def _row(id_: str, live, prd, retired) -> tuple[str, str, str]:
    if id_ in live:
        return id_, "live", live[id_]
    if id_ in retired:
        return id_, "retired", retired[id_] + " *(deleted, D-022)*"
    if id_ in prd:
        return id_, "designed", prd[id_] + " *(designed in PRD §7, never implemented)*"
    return id_, "unknown", "*no definition found*"


def _escape(cell: str) -> str:
    return cell.replace("|", "\\|")


def _link_to_decisions(rel: str) -> str:
    """Relative path from the doc being written to docs/decisions.md."""
    from os.path import relpath

    from_dir = str(Path(rel).parent)
    return relpath("docs/decisions.md", from_dir if from_dir != "." else "")


def build_block(text: str, live, prd, retired, decisions, want_scen, want_dec, rel) -> str:
    body = text.split(BEGIN)[0]
    lines = [BEGIN, "", "## What the ids on this page mean", ""]

    if want_scen:
        found = sorted(set(SCENARIO_RE.findall(body)))
        if found:
            lines += [
                "Eval scenarios. **live** runs today, so the question shown is the one",
                "`make eval` actually asks. **designed** was specified but never built.",
                "**retired** existed once and was deleted.",
                "",
                "| id | status | question |",
                "|---|---|---|",
            ]
            for id_ in found:
                i, status, q = _row(id_, live, prd, retired)
                lines.append(f"| `{i}` | {status} | {_escape(q)} |")
            lines.append("")

    if want_dec:
        found = sorted(set(DECISION_RE.findall(body)))
        if found:
            target = _link_to_decisions(rel)
            lines += [
                f"Decisions, recorded in full in [`docs/decisions.md`]({target}).",
                "",
                "| id | decision |",
                "|---|---|",
            ]
            for id_ in found:
                lines.append(
                    f"| `{id_}` | {_escape(decisions.get(id_, '*not found*'))} |"
                )
            lines.append("")

    lines.append(END)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if any doc is stale")
    args = parser.parse_args()

    live, prd, retired, decisions = (
        _live_scenarios(),
        _prd_scenarios(),
        _retired_scenarios(),
        _decisions(),
    )

    stale = []
    for rel, want_scen, want_dec in TARGETS:
        path = ROOT / rel
        if not path.exists():
            continue
        text = path.read_text()
        base = text.split(BEGIN)[0].rstrip()
        # Drop the separator this script itself added last time, or every run
        # stacks another one above the block. Caught by the idempotence test.
        while base.endswith("---"):
            base = base[: -len("---")].rstrip()
        base += "\n"
        block = build_block(
            text, live, prd, retired, decisions, want_scen, want_dec, rel
        )
        new = base + "\n---\n\n" + block + "\n"
        if new != text:
            if args.check:
                stale.append(rel)
            else:
                path.write_text(new)
                print(f"updated {rel}")

    if args.check and stale:
        print("stale id-reference block in: " + ", ".join(stale))
        print("run: python -m scripts.build_id_reference")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
